export const hall_data = [
  {
    name: "Boardroom",
    imageLink: "/images/variants/boardroom/main_photo.JPG",
    headerText: "Фото розстановки залу boradroom",
    photoList: [
      "/images/variants/boardroom/main_photo.JPG",
      "/images/variants/boardroom/1.JPG",
      "/images/variants/boardroom/2.JPG",
      "/images/variants/boardroom/3.JPG",
      "/images/variants/boardroom/4.JPG",
      "/images/variants/boardroom/5.JPG",
      "/images/variants/boardroom/6.JPG",
      "/images/variants/boardroom/7.JPG",
      "/images/variants/boardroom/8.JPG",
      "/images/variants/boardroom/9.JPG",
      "/images/variants/boardroom/10.JPG",
    ],
  },
  {
    name: "Classroom",
    imageLink: "/images/variants/classroom/main_photo.JPG",
    headerText: "Фото розстановки залу classroom",
    photoList: [
      "/images/variants/classroom/main_photo.JPG",
      "/images/variants/classroom/1.JPG",
      "/images/variants/classroom/2.JPG",
      "/images/variants/classroom/3.JPG",
      "/images/variants/classroom/4.JPG",
      "/images/variants/classroom/5.JPG",
      "/images/variants/classroom/6.JPG",
      "/images/variants/classroom/7.JPG",
      "/images/variants/classroom/8.JPG",
      "/images/variants/classroom/9.JPG",
      "/images/variants/classroom/10.JPG",
      "/images/variants/classroom/11.JPG",
      "/images/variants/classroom/12.JPG",
      "/images/variants/classroom/13.JPG",
      "/images/variants/classroom/14.JPG",
    ],
  },
  {
    name: "U_shape",
    imageLink: "/images/variants/u_shape/main_photo.JPG",
    headerText: "Фото розстановки залу U-Shape",
    photoList: [
      "/images/variants/u_shape/main_photo.JPG",
      "/images/variants/u_shape/1.JPG",
      "/images/variants/u_shape/2.JPG",
      "/images/variants/u_shape/3.JPG",
      "/images/variants/u_shape/4.JPG",
      "/images/variants/u_shape/5.JPG",
      "/images/variants/u_shape/6.JPG",
      "/images/variants/u_shape/7.JPG",
      "/images/variants/u_shape/8.JPG",
    ],
  },
  {
    name: "Banquet",
    imageLink: "/images/variants/banquet/main_photo.JPG",
    headerText: "Фото бенкетного залу",
    photoList: [
      "/images/variants/banquet/main_photo.JPG",
      "/images/variants/banquet/1.JPG",
      "/images/variants/banquet/2.JPG",
      "/images/variants/banquet/3.JPG",
      "/images/variants/banquet/4.JPG",
      "/images/variants/banquet/5.JPG",
      "/images/variants/banquet/6.JPG",
    ],
  },
  {
    name: "Reception",
    imageLink: "/images/variants/reception/main_photo.JPG",
    headerText: "Фото reception",
    photoList: [
      "/images/variants/reception/main_photo.JPG",
      "/images/variants/reception/1.JPG",
      "/images/variants/reception/2.JPG",
      "/images/variants/reception/3.JPG",
      "/images/variants/reception/4.JPG",
    ],
  },
];
